/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import pdf.PDF;
import mail.Mail;
import mail.MailSession;

/**
 *
 * @author mauri
 */
public class MainMenu extends javax.swing.JFrame {
//    Variables
    MailSession email_sesion = new MailSession();
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

//        Centrar la ventana
        this.setLocationRelativeTo(null);
        this.Panel_carta.setVisible(false);
        this.Panel_email.setVisible(false);
        this.Panel_documentos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Info = new javax.swing.JPanel();
        Matricula = new javax.swing.JPanel();
        text_field_search = new javax.swing.JTextField();
        label_search = new javax.swing.JLabel();
        botonBusqueda = new javax.swing.JButton();
        student_info = new javax.swing.JPanel();
        label_studentName = new javax.swing.JLabel();
        label_numberControl = new javax.swing.JLabel();
        student_name = new javax.swing.JLabel();
        student_number = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        btn_desplegarCarta = new javax.swing.JButton();
        btn_desplegarDocs = new javax.swing.JButton();
        btn_email = new javax.swing.JButton();
        Panel_email = new javax.swing.JPanel();
        label_titulo_email = new javax.swing.JLabel();
        email_asunto = new javax.swing.JTextField();
        label_asunto_email = new javax.swing.JLabel();
        email_mensaje = new javax.swing.JTextField();
        email_archivo = new javax.swing.JLabel();
        email_destinatario = new javax.swing.JTextField();
        label_email_email = new javax.swing.JLabel();
        label_txt_email1 = new javax.swing.JLabel();
        label_archivo_email1 = new javax.swing.JLabel();
        email_btn_enviar = new javax.swing.JButton();
        Panel_carta = new javax.swing.JPanel();
        btn_imprimirCarta = new javax.swing.JButton();
        btn_generarCarta = new javax.swing.JButton();
        label_tituloCarta = new javax.swing.JLabel();
        label_company = new javax.swing.JLabel();
        label_boss = new javax.swing.JLabel();
        label_boss_job = new javax.swing.JLabel();
        student_boss_job = new javax.swing.JTextField();
        student_company1 = new javax.swing.JTextField();
        student_boss_name = new javax.swing.JTextField();
        btn_close_letter = new javax.swing.JLabel();
        Panel_documentos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(31, 61, 109));
        Header.setPreferredSize(new java.awt.Dimension(800, 80));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Programa Dual");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matricula.setBackground(new java.awt.Color(255, 255, 255));
        Matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_field_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_searchActionPerformed(evt);
            }
        });
        Matricula.add(text_field_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, -1));

        label_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_search.setText("Numero de control:");
        Matricula.add(label_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        botonBusqueda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });
        Matricula.add(botonBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 30));

        student_info.setBackground(new java.awt.Color(255, 255, 255));
        student_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_studentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_studentName.setText("Alumno:");
        student_info.add(label_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        label_numberControl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_numberControl.setText("Numero de control:");
        student_info.add(label_numberControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        student_info.add(student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        student_info.add(student_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 30, -1, -1));

        Matricula.add(student_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 100));

        Info.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 140));

        buttons.setBackground(new java.awt.Color(255, 255, 255));
        buttons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_desplegarCarta.setText("Carta");
        btn_desplegarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desplegarCartaActionPerformed(evt);
            }
        });
        buttons.add(btn_desplegarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        btn_desplegarDocs.setText("Documentos");
        btn_desplegarDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desplegarDocsActionPerformed(evt);
            }
        });
        buttons.add(btn_desplegarDocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btn_email.setText("Email");
        btn_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emailActionPerformed(evt);
            }
        });
        buttons.add(btn_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Info.add(buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 370, 140));

        Fondo.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 140));

        Panel_email.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo_email.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_titulo_email.setText("Correo electrónico");
        Panel_email.add(label_titulo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        email_asunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_asuntoActionPerformed(evt);
            }
        });
        Panel_email.add(email_asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 550, -1));

        label_asunto_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_asunto_email.setText("Asunto:");
        Panel_email.add(label_asunto_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        email_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_mensajeActionPerformed(evt);
            }
        });
        Panel_email.add(email_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 540, -1));

        email_archivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_archivo.setText("Ninguno");
        Panel_email.add(email_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        email_destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_destinatarioActionPerformed(evt);
            }
        });
        Panel_email.add(email_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 470, -1));

        label_email_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_email_email.setText("Email Destinatario:");
        Panel_email.add(label_email_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        label_txt_email1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_txt_email1.setText("Mensaje:");
        Panel_email.add(label_txt_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        label_archivo_email1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_archivo_email1.setText("Archivo:");
        Panel_email.add(label_archivo_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        email_btn_enviar.setText("Enviar");
        email_btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_btn_enviarActionPerformed(evt);
            }
        });
        Panel_email.add(email_btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        Fondo.add(Panel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 700, 250));

        Panel_carta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_imprimirCarta.setText("Imprimir");
        btn_imprimirCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirCartaActionPerformed(evt);
            }
        });
        Panel_carta.add(btn_imprimirCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        btn_generarCarta.setText("Generar");
        btn_generarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarCartaActionPerformed(evt);
            }
        });
        Panel_carta.add(btn_generarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        label_tituloCarta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_tituloCarta.setText("Carta de presentación");
        Panel_carta.add(label_tituloCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        label_company.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_company.setText("Compañía:");
        Panel_carta.add(label_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        label_boss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_boss.setText("Dirigido a:");
        Panel_carta.add(label_boss, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        label_boss_job.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_boss_job.setText("Puesto:");
        Panel_carta.add(label_boss_job, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        student_boss_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_boss_jobActionPerformed(evt);
            }
        });
        Panel_carta.add(student_boss_job, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 530, -1));

        student_company1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_company1ActionPerformed(evt);
            }
        });
        Panel_carta.add(student_company1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 530, -1));

        student_boss_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_boss_nameActionPerformed(evt);
            }
        });
        Panel_carta.add(student_boss_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 530, -1));

        btn_close_letter.setBackground(new java.awt.Color(255, 51, 51));
        btn_close_letter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_close_letterMouseClicked(evt);
            }
        });
        Panel_carta.add(btn_close_letter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        Fondo.add(Panel_carta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 700, 220));
        Fondo.add(Panel_documentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 700, 240));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_field_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_searchActionPerformed

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed
        student_name.setText("Mauricio Ruiz Vaquera");
        student_number.setText("ITS");
    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void btn_desplegarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desplegarCartaActionPerformed
        this.Panel_carta.setVisible(true);
        this.Panel_email.setVisible(false);
        this.Panel_documentos.setVisible(false);

    }//GEN-LAST:event_btn_desplegarCartaActionPerformed

    private void btn_imprimirCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirCartaActionPerformed

    private void btn_generarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarCartaActionPerformed
        try {
            PDF.createPDF(student_name.getText(), student_number.getText(), "Sistemas", "GeneralMotors", "Ana Maria", "RH");
            JOptionPane.showMessageDialog(null, "PDF creado");
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_generarCartaActionPerformed

    private void btn_desplegarDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desplegarDocsActionPerformed
        this.Panel_carta.setVisible(false);
        this.Panel_email.setVisible(true);
        this.Panel_documentos.setVisible(false);
    }//GEN-LAST:event_btn_desplegarDocsActionPerformed

    private void btn_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emailActionPerformed
        if (MailSession.getMail() == null) {
            email_sesion.setVisible(true);
        } else {
            this.Panel_carta.setVisible(false);
            this.Panel_email.setVisible(false);
            this.Panel_documentos.setVisible(true);
        }

    }//GEN-LAST:event_btn_emailActionPerformed

    private void student_boss_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_boss_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_boss_jobActionPerformed

    private void student_company1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_company1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_company1ActionPerformed

    private void student_boss_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_boss_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_boss_nameActionPerformed

    private void btn_close_letterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close_letterMouseClicked
        this.Panel_carta.setVisible(false);
    }//GEN-LAST:event_btn_close_letterMouseClicked

    private void email_asuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_asuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_asuntoActionPerformed

    private void email_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_mensajeActionPerformed

    private void email_destinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_destinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_destinatarioActionPerformed

    private void email_btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_btn_enviarActionPerformed
        try {
            email_sesion.getMail().enviarEmail(email_asunto.getText(), email_mensaje.getText(), email_destinatario.getText());
            JOptionPane.showMessageDialog(null, "Mensaje enviado");
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(null, "Error al enviar mensaje");
        }
    }//GEN-LAST:event_email_btn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Info;
    private javax.swing.JPanel Matricula;
    private javax.swing.JPanel Panel_carta;
    private javax.swing.JPanel Panel_documentos;
    private javax.swing.JPanel Panel_email;
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JLabel btn_close_letter;
    private javax.swing.JButton btn_desplegarCarta;
    private javax.swing.JButton btn_desplegarDocs;
    private javax.swing.JButton btn_email;
    private javax.swing.JButton btn_generarCarta;
    private javax.swing.JButton btn_imprimirCarta;
    private javax.swing.JPanel buttons;
    private javax.swing.JLabel email_archivo;
    private javax.swing.JTextField email_asunto;
    private javax.swing.JButton email_btn_enviar;
    private javax.swing.JTextField email_destinatario;
    private javax.swing.JTextField email_mensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_archivo_email1;
    private javax.swing.JLabel label_asunto_email;
    private javax.swing.JLabel label_boss;
    private javax.swing.JLabel label_boss_job;
    private javax.swing.JLabel label_company;
    private javax.swing.JLabel label_email_email;
    private javax.swing.JLabel label_numberControl;
    private javax.swing.JLabel label_search;
    private javax.swing.JLabel label_studentName;
    private javax.swing.JLabel label_tituloCarta;
    private javax.swing.JLabel label_titulo_email;
    private javax.swing.JLabel label_txt_email1;
    private javax.swing.JTextField student_boss_job;
    private javax.swing.JTextField student_boss_name;
    private javax.swing.JTextField student_company1;
    private javax.swing.JPanel student_info;
    private javax.swing.JLabel student_name;
    private javax.swing.JLabel student_number;
    private javax.swing.JTextField text_field_search;
    // End of variables declaration//GEN-END:variables
}
