/*
 * Copyright 2022 Chipa & Alan G.
 * MainMenu es la ventana principal para poder realizar distintas operaciones
 */
package ventanas;

import BD.BDSentences;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import pdf.PDF;
import mail.MailSession;

/**
 *
 * @author mauri
 */
public class MainMenu extends javax.swing.JFrame {
//    Variables

    private MailSession email_sesion = new MailSession();
    private BDSentences bd = null;
    private String nombreAlumno = "";

    /**
     * Creates new form MainMenu
     *
     * @param bd
     */
    public MainMenu(BDSentences bd) {
        initComponents();
        this.bd = bd;

//        Centrar la ventana
        this.setLocationRelativeTo(null);
        this.Panel_carta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Fondo = new javax.swing.JPanel();
        Info = new javax.swing.JPanel();
        Matricula = new javax.swing.JPanel();
        text_field_search = new javax.swing.JTextField();
        label_search = new javax.swing.JLabel();
        botonBusqueda = new javax.swing.JButton();
        student_info = new javax.swing.JPanel();
        label_studentName = new javax.swing.JLabel();
        label_numberControl = new javax.swing.JLabel();
        student_name = new javax.swing.JLabel();
        student_number = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        btn_desplegarCarta = new javax.swing.JButton();
        btn_desplegarDocs = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Panel_carta = new javax.swing.JPanel();
        btn_imprimirCarta = new javax.swing.JButton();
        btn_generarCarta = new javax.swing.JButton();
        label_tituloCarta = new javax.swing.JLabel();
        label_company = new javax.swing.JLabel();
        label_boss = new javax.swing.JLabel();
        label_boss_job = new javax.swing.JLabel();
        student_boss_job = new javax.swing.JTextField();
        student_company = new javax.swing.JTextField();
        student_boss_name = new javax.swing.JTextField();
        btn_close_letter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(31, 61, 109));
        Header.setPreferredSize(new java.awt.Dimension(800, 80));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/logo_its_60.png"))); // NOI18N
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Programa Dual");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Header.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matricula.setBackground(new java.awt.Color(255, 255, 255));
        Matricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Matricula.add(text_field_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, -1));

        label_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_search.setText("Numero de control:");
        Matricula.add(label_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        botonBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("./images/buttons/search_button.png")));
        botonBusqueda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });
        Matricula.add(botonBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 30));

        student_info.setBackground(new java.awt.Color(255, 255, 255));
        student_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_studentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_studentName.setText("Alumno:");
        student_info.add(label_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        label_numberControl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_numberControl.setText("Numero de control:");
        student_info.add(label_numberControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        student_info.add(student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        student_info.add(student_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        Matricula.add(student_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 100));

        Info.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 140));

        buttons.setBackground(new java.awt.Color(255, 255, 255));
        buttons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_desplegarCarta.setText("Carta");
        btn_desplegarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desplegarCartaActionPerformed(evt);
            }
        });
        buttons.add(btn_desplegarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        btn_desplegarDocs.setText("Documentos");
        btn_desplegarDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desplegarDocsActionPerformed(evt);
            }
        });
        buttons.add(btn_desplegarDocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttons.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jButton2.setText("Alumnos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttons.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        Info.add(buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 380, 140));

        Fondo.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 140));

        Panel_carta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_imprimirCarta.setText("Imprimir");
        btn_imprimirCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirCartaActionPerformed(evt);
            }
        });
        Panel_carta.add(btn_imprimirCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        btn_generarCarta.setText("Generar");
        btn_generarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarCartaActionPerformed(evt);
            }
        });
        Panel_carta.add(btn_generarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        label_tituloCarta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_tituloCarta.setText("Carta de presentación");
        Panel_carta.add(label_tituloCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        label_company.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_company.setText("Compañía:");
        Panel_carta.add(label_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        label_boss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_boss.setText("Dirigido a:");
        Panel_carta.add(label_boss, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        label_boss_job.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_boss_job.setText("Puesto:");
        Panel_carta.add(label_boss_job, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        student_boss_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_boss_jobActionPerformed(evt);
            }
        });
        Panel_carta.add(student_boss_job, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 530, -1));

        student_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_companyActionPerformed(evt);
            }
        });
        Panel_carta.add(student_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 530, -1));

        student_boss_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_boss_nameActionPerformed(evt);
            }
        });
        Panel_carta.add(student_boss_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 530, -1));

        btn_close_letter.setBackground(new java.awt.Color(255, 51, 51));
        btn_close_letter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_close_letterMouseClicked(evt);
            }
        });
        Panel_carta.add(btn_close_letter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        Fondo.add(Panel_carta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 700, 220));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed
        if (text_field_search.getText().equals("")) {
            return;
        }
        if (text_field_search.getText().length() < 8 || text_field_search.getText().length() > 8) {
            JOptionPane.showMessageDialog(null, "La matricula debe ser de 8 caracteres");
            return;
        }
        try {
            bd.Busqueda(text_field_search.getText());
            nombreAlumno = bd.getNombre_alumno() + " " + bd.getAlumno_apellido_pat() + " " + bd.getAlumno_apellido_mat();
            student_name.setText(nombreAlumno);
            student_number.setText(bd.getAlumno_matricula());
        } catch (SQLException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void btn_desplegarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desplegarCartaActionPerformed
        this.Panel_carta.setVisible(true);

    }//GEN-LAST:event_btn_desplegarCartaActionPerformed

    private void btn_imprimirCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirCartaActionPerformed

    private void btn_generarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarCartaActionPerformed
        if(nombreAlumno.equals("")){
            JOptionPane.showMessageDialog(null, "No hay ningun alumno seleccionado");
            return;
        }
        try {
            PDF.createPDF(nombreAlumno, bd.getAlumno_matricula(), bd.getCarrera(),bd.getSeguroSocial(), student_company.getText(), student_boss_name.getText(), student_boss_job.getText());
            JOptionPane.showMessageDialog(null, "PDF creado");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al crear el PDF");
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_generarCartaActionPerformed

    private void btn_desplegarDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desplegarDocsActionPerformed
        try {
            Desktop.getDesktop().open(new File("E:\\Usuario\\Documentos\\archivos_alumnos\\"));
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_desplegarDocsActionPerformed

    private void student_boss_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_boss_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_boss_jobActionPerformed

    private void student_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_companyActionPerformed

    private void student_boss_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_boss_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_boss_nameActionPerformed

    private void btn_close_letterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close_letterMouseClicked
        this.Panel_carta.setVisible(false);
    }//GEN-LAST:event_btn_close_letterMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistrarAlumno ra = new RegistrarAlumno(bd);
        ra.setVisible(true);
        ra.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tabla ta = new Tabla(bd);
        ta.setVisible(true);
        ta.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Info;
    private javax.swing.JPanel Matricula;
    private javax.swing.JPanel Panel_carta;
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JLabel btn_close_letter;
    private javax.swing.JButton btn_desplegarCarta;
    private javax.swing.JButton btn_desplegarDocs;
    private javax.swing.JButton btn_generarCarta;
    private javax.swing.JButton btn_imprimirCarta;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_boss;
    private javax.swing.JLabel label_boss_job;
    private javax.swing.JLabel label_company;
    private javax.swing.JLabel label_numberControl;
    private javax.swing.JLabel label_search;
    private javax.swing.JLabel label_studentName;
    private javax.swing.JLabel label_tituloCarta;
    private javax.swing.JTextField student_boss_job;
    private javax.swing.JTextField student_boss_name;
    private javax.swing.JTextField student_company;
    private javax.swing.JPanel student_info;
    private javax.swing.JLabel student_name;
    private javax.swing.JLabel student_number;
    private javax.swing.JTextField text_field_search;
    // End of variables declaration//GEN-END:variables
}
