/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mail;

import java.io.IOException;
import java.security.InvalidParameterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;

/**
 *
 * @author mauri
 */
public class MailSession extends javax.swing.JFrame {
    private static Mail email;

    /**
     * Creates new form MailSession
     */
    public MailSession() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        btn_close_letter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        InicioSesion = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        field_user = new javax.swing.JTextField();
        usuario1 = new javax.swing.JLabel();
        field_password = new javax.swing.JPasswordField();
        btn_enter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(31, 61, 109));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close_letter.setBackground(new java.awt.Color(255, 51, 51));
        btn_close_letter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_close_letterMouseClicked(evt);
            }
        });
        Header.add(btn_close_letter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio de sesión correo");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioSesion.setBackground(new java.awt.Color(243, 243, 243));
        InicioSesion.setName(""); // NOI18N
        InicioSesion.setPreferredSize(new java.awt.Dimension(400, 350));
        InicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario.setText("Correo electrónico");
        InicioSesion.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        field_user.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        field_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_userActionPerformed(evt);
            }
        });
        InicioSesion.add(field_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 230, -1));

        usuario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario1.setText("Contraseña");
        InicioSesion.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        InicioSesion.add(field_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, -1));

        btn_enter.setBackground(new java.awt.Color(31, 61, 109));
        btn_enter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(255, 255, 255));
        btn_enter.setText("Ingresar");
        btn_enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_enterMouseClicked(evt);
            }
        });
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        InicioSesion.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 230, 30));

        Fondo.add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 200));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_userActionPerformed

    private void btn_enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enterMouseClicked

    }//GEN-LAST:event_btn_enterMouseClicked

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        try {
            email = new Mail("config/configuracion.prop",field_user.getText(), field_password.getText());
            dispose();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_enterActionPerformed

    private void btn_close_letterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close_letterMouseClicked
        dispose();
    }//GEN-LAST:event_btn_close_letterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MailSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MailSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MailSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailSession().setVisible(true);
            }
        });
    }
    
    public static Mail getMail(){
        return email;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JLabel btn_close_letter;
    private javax.swing.JButton btn_enter;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JTextField field_user;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables
}
